env:
  browser: true
  es6: true
  jest: true

extends:
  - "plugin:react/recommended"
  - "plugin:mocha/recommended"

parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - import
  - mocha
  - promise
  - react
rules:
  complexity: ["warn", 10]
  no-console:
    - error
    - allow:
      - warn
      - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  react/jsx-uses-vars: 1
  semi:
    - error
    - always

settings:
  react:
    version: 17.0.2
