version: 2
jobs:
  build:
    working_directory: ~/wayback-diff
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run linter
          command: eslint src/
      - run:
          name: Test
          command: CI=true yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
