version: 2
jobs:
  build:
    working_directory: ~/wayback-diff
    docker:
      - image: cimg/node:20.6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: yarn install --dev
      - save_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          # Note that eslint run before every test run due to `pretest` in
          # `package.json`.
          name: Test
          command: CI=true yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
